### ISSUE TITLE
I got an issue when using it.

### ISSUE THREAD

**Issue by SirPytan** [ejektaflex/KambrikDocs#1]
Here the Log file, I will also add a screenshot: https://paste.ee/p/1nJFK

![image](https://user-images.githubusercontent.com/38554289/134257657-8f20b124-fc9f-4b3e-8213-a9ba14b2e9dd.png)

**Comment by ejektaflex** [comment]
```
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "net.minecraft.class_2960.moenchantments$oldIdentifier" is null
	at net.minecraft.class_2960.handler$bpe000$moenchantments_fix_id(class_2960.java:1517)
	at net.minecraft.class_2960.<init>(class_2960.java:34)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at net.minecraft.class_2583.<clinit>(class_2583.java:23)
```
I believe that it is Mo' Enchantments causing this problem. I'm not sure what they're doing during my prelaunch, but something of theirs causes crashes when it's run before it is supposed to. Seems to be that they are [mixing into the `Identifier` class and the mixin fails](https://gitlab.com/biom4st3r/moenchantments/-/blob/1.17/more-enchantments/src/main/java/com/biom4st3r/moenchantments/mixin/notadatafixer/Identifiermxn.java#L21).

They're using a weird hack to rewrite Identifiers during runtime whenever they encounter an old Identifier, probably because they don't use the old one anymore and this is a weird attempt to keep old version compatibility... And this solution is not what I would recommend, as clever as it is.

At the end of the day, using Identifiers during prelaunch is sensible and does not require a Minecraft context - their mixin is causing the crash, so it's a Mo Enchantments problem.
